import cProfile
import io
import os
import pstats

os.environ["RAY_DEDUP_LOGS"] = "0"
import ray
from ray import tune, train
import ray.rllib
from ray.rllib.algorithms.ppo import PPOConfig, PPO, PPO
from ray import shutdown

# from gym_envs.envs.hierarchical_env import HierarchicalEnv
from gym_envs.envs.blind_env import BlindEnv
from gym_envs.envs.shop_env import ShopEnv
from ray.rllib.policy.view_requirement import ViewRequirement
from ray.rllib.policy.torch_policy_v2 import TorchPolicyV2
from ray.rllib.policy.sample_batch import SampleBatch
from ray.air import RunConfig

from copy import deepcopy
from ray.tune.search.bayesopt import BayesOptSearch

from modeling.generic_blind_model import BalatroBlindModel as GenericBalatroBlindModel
from modeling.generic_shop_model import BalatroShopModel as GenericBalatroShopModel
from modeling.distributions import (
    ARBinaryDistribution,
    ARChooseOrStopDistribution,
    ARChooseOrStopStackedDistribution,
    DualSubsetDistribution,
    ExpertModeCountsDistribution,
    ExpertOptionsDistribution,
    LinearExpertsDistribution,
    ModeCountBinaryDistribution,
    PlayDiscardBinaryDistribution,
    ShopActionAndHandTargetsDistribution,
    SparseSubsetAndMaskDistribution,
)
from modeling.gumbel_noise_sampler import GumbelNoiseSamplerDist
from ray.rllib.models import ModelCatalog
from ray.tune.registry import register_env, register_trainable
from ray.rllib.policy.torch_policy_v2 import TorchPolicyV2

from gymnasium import spaces as sp
from ray.rllib.algorithms.algorithm import Algorithm
from gym_envs.envs.blind_env import BlindEnv
from gym_envs.envs.blind_shop_env import BlindShopEnv

import numpy as np
import torch
from gym_envs.round_logger_callback import RoundLoggerCallback

from numpy import array, float32
from ray.tune.search.optuna import OptunaSearch
from ray.rllib.core.rl_module.rl_module import SingleAgentRLModuleSpec
from ray.rllib.core.rl_module.marl_module import MultiAgentRLModuleSpec
import os
from ray.air.integrations.wandb import WandbLoggerCallback, setup_wandb
import wandb
from typing import Dict as typed_dict
from gym_envs.components.deck import Deck, ErraticDeck
from ray.rllib.algorithms.ppo.ppo_torch_policy import PPOTorchPolicy

from ray.air.config import CheckpointConfig

os.environ["WANDB_SILENT"] = "true"


class CuriosityTorchPolicy(PPOTorchPolicy):
    def __init__(self, obs_space, act_space, config):
        super().__init__(obs_space, act_space, config)

        # register your two new columns for training batches
        # self.view_requirements["hand_scores_aux_output"] = ViewRequirement(
        #     data_col="hand_scores_aux_output",
        #     shift=0,  # exact same timestep
        #     used_for_compute_actions=False,
        #     used_for_training=True,  # include in postprocessed SampleBatch
        # )
        # self.view_requirements["has_jokers"] = ViewRequirement(
        #     data_col="has_jokers",
        #     shift=0,
        #     used_for_compute_actions=False,
        #     used_for_training=True,
        # )

    def extra_action_out(self, input_dict, state_batches, model, action_dist):
        info = super().extra_action_out(input_dict, state_batches, model, action_dist)
        # grab your stored aux preds off the model
        # if hasattr(model, "play_aux") and hasattr(model, "_has_jokers"):
        #     info["hand_scores_aux_output"] = model.play_aux
        #     info["has_jokers"] = model._has_jokers
        return info


# 2) Subclass PPO to return that policy as its default
class CuriosityPPO(PPO):
    @classmethod
    def get_default_policy_class(cls, config):
        return CuriosityTorchPolicy


def policy_mapping(agent_id, episode, **kwargs):
    if agent_id == "blind":
        return "blind_policy"
    else:
        return "shop_policy"


def flatten_dict(d, parent_key="", sep="/"):
    items = []
    for k, v in d.items():
        new_key = f"{parent_key}{sep}{k}" if parent_key else k
        if isinstance(v, typed_dict):
            v = dict(v)
        if isinstance(v, dict):
            items.extend(flatten_dict(v, new_key, sep=sep).items())
        elif isinstance(v, (int, float, str, bool)):
            items.append((new_key, v))
    return dict(items)


def log_results(i, result):
    # Remove some redundant keys from the result dict
    # Not sure why rllib even makes these honestly, maybe they will matter later?
    keys_to_remove = ["sampler_results", "env_runner_results"]
    for key in keys_to_remove:
        if key in result:
            del result[key]
    keys_to_remove = []
    for key in result["custom_metrics"]:
        # Remove autogenerated min and max keys
        if key.endswith("_min") or key.endswith("_max"):
            keys_to_remove.append(key)
    for key in keys_to_remove:
        del result["custom_metrics"][key]
    wandb.log(
        flatten_dict(result),
        step=i,
        commit=i % 5 == 0,  # Commit every 10 steps
    )


# dummy test environment for testing purposes
# Doesn't actually have any way of validating that the agent is doing the right thing
def shop_config(model_config={}):
    env_config = {}
    config = (
        PPOConfig()
        .environment(
            env=ShopEnv,
            env_config=env_config,
            observation_space=ShopEnv(env_config).build_observation_space(),
            action_space=ShopEnv(env_config).build_action_space(),
        )
        # .callbacks(RoundLoggerCallback)
        .framework("torch")
        .resources(num_gpus=1, num_cpus_per_worker=1)
        .env_runners(
            num_env_runners=1,
            num_envs_per_env_runner=1,
            sample_timeout_s=60,
            rollout_fragment_length="auto",
            batch_mode="complete_episodes",
        )
        .training(
            train_batch_size=int(2**10),
            sgd_minibatch_size=int(2**10),
            num_sgd_iter=1,
            lr=2e-4,
            grad_clip=0.5,
            clip_param=0.3,
            kl_coeff=0.0,
            vf_loss_coeff=0.5,
            vf_clip_param=10.0,
            entropy_coeff=0.00,
            lambda_=0.95,
            gamma=0.99,
            model=model_config,
        )
        # .evaluation(
        #     evaluation_num_env_runners=1,
        #     evaluation_interval=1,
        #     evaluation_config={"explore": False},
        #     evaluation_parallel_to_training=True,
        #     evaluation_duration="auto",
        # )
    )

    return config


def blind_config(
    blind_env_config={},
    blind_model_config={},
):
    hand_size = 8
    config = (
        PPOConfig()
        .environment(
            env=BlindEnv,
            env_config=blind_env_config,
            observation_space=BlindEnv(blind_env_config).observation_space,
            action_space=BlindEnv(blind_env_config).action_space,
        )
        .callbacks(RoundLoggerCallback)
        .framework("torch", torch_compile_learner=True)
        .resources(
            num_gpus=1,
            num_cpus_per_worker=1,
        )
        .env_runners(
            num_env_runners=14,
            num_envs_per_env_runner=100,
            sample_timeout_s=60,
            rollout_fragment_length="auto",
            # This would be good to use, but it breaks certain data passed to the model
            # e.g. card indices that need to be passed into the embedding layer
            # observation_filter="MeanStdFilter",
            batch_mode="complete_episodes",
        )
        .training(
            train_batch_size=int(2**13),
            sgd_minibatch_size=int(2**11),
            num_sgd_iter=10,
            lr=2e-4,
            # lr=tune.loguniform(1e-5, 1e-3),
            grad_clip=0.5,
            clip_param=0.1,
            kl_coeff=0.0,
            vf_loss_coeff=0.5,
            vf_clip_param=10.0,
            entropy_coeff=0.00,
            # entropy_coeff=tune.loguniform(0.0001, 0.02),
            lambda_=0.95,
            gamma=0.99,
            model=blind_model_config,
        )
        # .evaluation(
        #     evaluation_num_env_runners=1,
        #     evaluation_interval=1,
        #     evaluation_config={"explore": False},
        #     evaluation_parallel_to_training=True,
        #     evaluation_duration="auto",
        # )
    )

    return config


def blind_shop_config(
    blind_env_config={},
    blind_model_config={},
    blind_shop_env_config={},
    shop_model_config={},
):
    smoke = False
    blind_env = BlindEnv(blind_env_config)
    shop_env = ShopEnv(blind_shop_env_config["shop_env_config"])

    remote_env = blind_shop_env_config.get("connect_to_balatro", False)
    eval_env_config = deepcopy(blind_shop_env_config)
    eval_env_config["shop_starts_enabled"] = True  # Enable shop starts for evaluation
    eval_env_config["catchup_probability"] = 0.0  # Disable catchup for evaluation
    eval_env_config["shop_env_config"][
        "ignore_rarity"
    ] = False  # Don't ignore rarity in evaluation

    POLICIES = {
        "blind_agent": (
            None,
            blind_env.observation_space,
            blind_env.action_space,
            {
                "model": blind_model_config,
                # "kl_target": 0.02,
                "kl_coeff": 0.0,
                "explore": not remote_env,
                "lambda_": 0.99,
                # "entropy_coeff": 0.001,
                # "entropy_coeff_schedule": [
                #     [0, 0.02],
                #     [3e5, 0.01],
                #     [2e6, 0.01],
                #     [6e6, 0.001],
                #     [1e7, 0.0001],
                # ],
            },
        ),
        "shop_agent": (
            None,
            shop_env.observation_space,
            shop_env.action_space,
            {
                "model": shop_model_config,
                # "entropy_coeff": 0.01,
                "kl_coeff": 0.0,
                "entropy_coeff": 0.01,
                "entropy_coeff_schedule": [[0, 0.01], [2e5, 0.003], [1e6, 0.0]],
                # "lr": 5e-4,
                "explore": not remote_env,
                "lambda_": 0.95,
            },
        ),
    }

    def policy_mapper(agent_id, episode, **kwargs):
        if "-" in agent_id:
            agent_id = agent_id.split("-")[0]
        return agent_id

    config = (
        PPOConfig(CuriosityPPO)
        .environment(
            env=BlindShopEnv,
            env_config=blind_shop_env_config,
        )
        .callbacks(RoundLoggerCallback)
        .framework("torch")
        .experimental(_enable_new_api_stack=False)
        .resources(num_gpus=1, num_cpus_per_worker=1)  # , num_cpus_for_local_worker=10)
        .env_runners(
            num_env_runners=(10 if not remote_env and not smoke else 0),
            # num_env_runners=0,
            num_envs_per_env_runner=6 if not remote_env and not smoke else 1,
            # num_envs_per_env_runner=10,
            explore=not remote_env,
            sample_timeout_s=60,
            rollout_fragment_length="auto",
            # rollout_fragment_length=128,
            # This would be good to use, but it breaks certain data passed to the model
            # e.g. card indices that need to be passed into the embedding layer
            # observation_filter="MeanStdFilter",
            batch_mode="complete_episodes",
        )
        .multi_agent(
            policies=POLICIES,
            policy_mapping_fn=policy_mapper,
            policies_to_train=(
                ["shop_agent", "blind_agent"]
                if not remote_env
                else []  # remote env is for demo only, not training
            ),
        )
        .training(
            train_batch_size=int(2**15),
            sgd_minibatch_size=int(2**11),
            num_sgd_iter=3,
            # lr_schedule=[[0, 1e-3], [1e6, 1e-4]],
            lr=1e-4,
            grad_clip=3,
            clip_param=0.3,
            vf_clip_param=3,
            entropy_coeff=0.001,
            gamma=0.99,
            vf_loss_coeff=0.25,
        )
    )

    if not remote_env and not smoke:
        config = config.evaluation(
            evaluation_num_env_runners=2,
            evaluation_interval=1,
            evaluation_config={"explore": False, "env_config": eval_env_config},
            evaluation_parallel_to_training=True,
            evaluation_duration="auto",
        )

    return config


if __name__ == "__main__":
    # model_name = "ppo_play_hand_type"
    # torch.autograd.set_detect_anomaly(True)
    ray.init(ignore_reinit_error=True)

    ModelCatalog.register_custom_action_dist(
        "play_discard_binary_dist", PlayDiscardBinaryDistribution
    )
    ModelCatalog.register_custom_action_dist(
        "auto_regressive_binary_dist", ARBinaryDistribution
    )
    ModelCatalog.register_custom_action_dist(
        "ar_choose_or_stop_dist", ARChooseOrStopDistribution
    )
    ModelCatalog.register_custom_action_dist(
        "ar_choose_or_stop_stacked_dist", ARChooseOrStopStackedDistribution
    )
    ModelCatalog.register_custom_action_dist(
        "linear_experts_dist", LinearExpertsDistribution
    )
    ModelCatalog.register_custom_action_dist(
        "expert_options_dist", ExpertOptionsDistribution
    )
    ModelCatalog.register_custom_action_dist(
        "mode_count_binary_dist", ModeCountBinaryDistribution
    )
    ModelCatalog.register_custom_action_dist(
        "shop_action_and_hand_targets_dist", ShopActionAndHandTargetsDistribution
    )
    ModelCatalog.register_custom_action_dist(
        "gumbel_noise_sampler", GumbelNoiseSamplerDist
    )
    ModelCatalog.register_custom_action_dist(
        "expert_mode_counts_dist", ExpertModeCountsDistribution
    )

    ModelCatalog.register_custom_model("generic_blind_model", GenericBalatroBlindModel)
    ModelCatalog.register_custom_model("generic_shop_model", GenericBalatroShopModel)
    ModelCatalog.register_custom_action_dist("dual_subset", DualSubsetDistribution)
    ModelCatalog.register_custom_action_dist(
        "sparse_subset_and_mask_dist", SparseSubsetAndMaskDistribution
    )

    max_jokers = 5
    max_hand_size = 10
    target_hand_reward = 0
    num_experts = 3  # Number of experts for the intent vectors model
    subset_hand_types = None  # "obs", "aux", None
    subset_scoring_cards = None
    demo_mode = False
    shared_encoder = False

    blind_action_dist = "ar_choose_or_stop_stacked_dist"
    action_mode_lookup = {
        "mode_count_binary_dist": "mode_count_binary",
        "play_discard_binary_dist": "multi_binary",
        "expert_mode_counts_dist": "expert_mode_counts",
        "dual_subset": "dual_subset",
        "sparse_subset_and_mask_dist": "play_subset_discard_mask",
        "ar_choose_or_stop_stacked_dist": "stacked_binary_masks",
    }

    blind_env_config = {
        "objective_mode": "blind_grind",  # "one_hand_easy", "blind_grind"
        "max_hand_size": max_hand_size,
        "action_mode": action_mode_lookup[blind_action_dist],
        # "action_mode": "subset_index",
        "hand_mode": "base_card",
        "num_experts": num_experts,
        "correct_reward": 1.0,
        "incorrect_penalty": 0.0,
        "discard_potential_reward": 0.00,
        "goal_progress_reward": 0.5,
        "suit_homogeneity_bonus": 0.1,
        "joker_synergy_bonus": 0.00,
        "discard_penalty": 0.0,  # negative penalty = reward for discarding
        "flattened_rank_chips": False,
        "cannot_discard_obs": True,
        "contained_hand_types_obs": True,
        "subset_hand_types_obs": subset_hand_types is not None,
        "scoring_cards_mask_obs": subset_scoring_cards is not None,
        "force_play": True,
        "chips_reward_weight": 1.0 / 1000,
        "hand_type_reward_weight": target_hand_reward,
        "infinite_deck": False,
        "bias": 0.0,
        "rarity_bonus": 0.0,
        "target_hand_obs": target_hand_reward > 0.0,
        "max_jokers": max_jokers,
        "chip_reward_normalization": "log_joker",
        "expert_pretraining": False,
        "deck_obs": False,
        "deck_counts_obs": False,
        "imagined_trajectories": False,
        "deck_cls": Deck,  # Deck class to use for the environment
        "joker_count_range": (0, 0),
        "hand_level_range": (1, 1),
        "hand_level_randomization": None,
        "joker_count_bias_exponent": 2,
        "round_range": (
            1,
            1,
        ),  # Defines starting round. Usually (1, 1), but can be changed for curriculum or testing
    }

    blind_model_config = {
        "custom_model": "generic_blind_model",
        "custom_action_dist": blind_action_dist,
        # "custom_action_dist": "gumbel_noise_sampler",
        "custom_model_config": {
            "embed_cards": True,
            "card_embedding_size": 64,
            "embed_suits_ranks": "learned",  # None, "learned", "manual", "manual_learned"
            "hidden_size": 256,
            "hidden_layer_count": 2,
            "self_attention_layers": 2,
            "self_attention_heads": 4,
            "action_method": "autoregressive",  # "intent_vectors" "linear_logits" "autoregressive" "convolutional" "linear_experts" "subset_convolution"
            "discard_as_intent": True,
            "hand_representation_method": "context_token",
            "jokers_in_hand_attention": False,
            # "ar_head_hidden_size": 256, # deprecated, right now we use the card_embedding_size for the AR context token
            "num_experts": num_experts,
            "max_jokers": max_jokers,
            "max_supported_hand_size": max_hand_size,
            "joker_types": 151,
            "forced_play_head": False,  # Separate head for discarding on 0 discards by playing
            "subset_hand_types": subset_hand_types,
            "scoring_cards_masks": subset_scoring_cards,
            "FiLM_mode": None,
            "deck_obs": False,
            "shared_encoder": shared_encoder,
            "noisy_layers": [],  # "attention"
            "allow_illegal_actions": False,
            "valid_card_count_coeff": 0.000,
            "suit_rank_entropy_coeff": 0.000,
            "suit_matching_aux_coeff": 0.0,
            "rank_matching_aux_coeff": 0.0,
            "option_variation_coeff": 0.000,
            "available_hand_types_coeff": 0.00,
            "intent_similarity_coeff": 0.0,
            "joker_identity_coeff": 0.00,
            "suit_count_aux_coeff": 0.00,
            "weight_decay_coeff": 0.0000,
            "hand_score_aux_coeff": 0.0,
            "joker_spread_loss_coeff": 0.00,
        },
    }

    shop_model_config = {
        "custom_model": "generic_shop_model",
        "custom_action_dist": "shop_action_and_hand_targets_dist",
        "custom_model_config": {
            "max_hand_size": max_hand_size,
            "card_embedding_size": 64,
            "attention_layers": 1,
            "attention_heads": 4,
            "action_head_depth": 2,
            "action_method": "convolutional",  # "convolutional", "intent_vectors"
            "shared_encoder": shared_encoder,
        },
    }

    blind_shop_env_config = {
        "start_phase": "blind",
        "stake": 0,
        "shop_starts_enabled": True,
        "cash_gained_reward": 0.001,
        "run_win_reward": 0.2,
        "round_won_reward": 1.0,
        "blind_env_config": blind_env_config,
        "shop_env_config": {"ignore_rarity": True, "max_hand_size": max_hand_size},
        "connect_to_balatro": demo_mode,
        "cycle_blind_agents": True,
        "truncate_blind_agents": False,
        "catchup_probability": 0.0,  # Probability of starting the episode mid run at a random round, with random initial conditions
    }

    training_mode = "blind_shop"
    if training_mode == "blind":
        config = blind_config(
            blind_env_config=blind_env_config,
            blind_model_config=blind_model_config,
        )
    elif training_mode == "shop_only":
        config = shop_config({"custom_model": "generic_shop_model"})
    elif training_mode == "blind_shop":
        max_jokers = 5
        config = blind_shop_config(
            blind_env_config=blind_env_config,
            blind_model_config=blind_model_config,
            blind_shop_env_config=blind_shop_env_config,
            shop_model_config=shop_model_config,
        )

    def set_curr_func(round_range, jokers=(0, 0)):
        def set_ranges(env):
            env.round_range = round_range
            env.joker_count_range = jokers

        return set_ranges

    zero_joker_baseline = r"C:\Users\giewe\AppData\Roaming\Balatro\Mods\balatrobot\run_data\blind_shop\blind_shop_01510_00000_0_2025-07-04_18-07-14\checkpoint_000060"
    one_joker_baseline = r"C:\Users\giewe\AppData\Roaming\Balatro\Mods\balatrobot\run_data\blind_shop\blind_shop_62d60_00000_0_2025-07-08_07-28-08\checkpoint_000010"
    shop_baseline = r"C:\Users\giewe\AppData\Roaming\Balatro\Mods\balatrobot\run_data\blind_shop\blind_shop_82cab_00000_0_2025-08-11_20-53-23\checkpoint_000004"
    green_stake_baseline = r"C:\Users\giewe\AppData\Roaming\Balatro\Mods\balatrobot\run_data\blind_shop\blind_shop_eef66_00000_0_2025-07-22_15-43-41\checkpoint_000006"

    # tuner = tune.Tuner(
    #     CuriosityPPO,
    #     param_space=config,
    #     run_config=RunConfig(
    #         name=training_mode,
    #         stop={"training_iteration": 1000},
    #         callbacks=[],
    #         storage_path=r"C:\Users\giewe\AppData\Roaming\Balatro\Mods\balatrobot\run_data",
    #         # trial_name_creator=lambda trial: f"{training_mode}_{trial.trial_id}",
    #         checkpoint_config=CheckpointConfig(num_to_keep=10, checkpoint_frequency=10),
    #     ),
    # )
    # tuner.fit()

    # algo = config.build()  # <-- config stays an AlgorithmConfig
    # for i in range(1000):
    #     result = algo.train()  # <-- all private flags are intact
    #     print(f"Iter {i}: reward_mean={result['episode_reward_mean']}")

    tune.run(
        CuriosityPPO,
        config=config,
        name=training_mode,
        # stop={"training_iteration": 1},
        callbacks=[
            WandbLoggerCallback(
                project="balatro-rl", log_config=True, save_checkpoints=False
            ),
        ],
        # local_dir=r"C:\Users\giewe\AppData\Roaming\Balatro\Mods\balatrobot\run_data",
        storage_path=r"C:\Users\giewe\AppData\Roaming\Balatro\Mods\balatrobot\run_data",
        trial_name_creator=lambda trial: f"{training_mode}_{trial.trial_id}",
        # restore=shop_baseline,
        checkpoint_config=CheckpointConfig(num_to_keep=10, checkpoint_frequency=10),
        # reuse_actors=True,
    )

    # results = tune.run(
    #     "PPO",
    #     config=config,
    #     stop={"time_total_s": 600},
    #     # resources_per_trial={"gpu": 0.25},
    #     # resources_per_trial={"cpu": 2},
    #     # checkpoint_at_end=True,
    #     # checkpoint_freq=50,
    #     num_samples=-1,
    #     # search_alg=BayesOptSearch(metric="episode_reward_mean", mode="max"),
    #     search_alg=OptunaSearch(
    #         metric="custom_metrics/0_jokers_round_mean", mode="max"
    #     ),
    #     # local_dir=f"model_snapshots/{model_name}",
    #     callbacks=[
    #         WandbLoggerCallback(
    #             project="balatro-rl", log_config=True, save_checkpoints=True
    #         ),
    #     ],
    #     trial_dirname_creator=lambda trial: f"{trial.trial_id}",
    # )
